# model/tokenizer
model_name: "/usr/ssd/llama-7b/"
tokenizer_name: "/usr/ssd/llama-7b/"
gradient_checkpointing: false
save_name: "nomic-ai/gpt4all-lora-multi-turn"

# dataset
streaming: false
num_proc: 64
dataset_path: "/usr/ssd/data/"
max_length: 256
batch_size: 4
lora: true

# train dynamics
lr: 5.0e-5
eval_every: 2000
eval_steps: 100
save_every: 2000
output_dir: "ckpts/gpt4all-lora-multi"
checkpoint: null
warmup_steps: 100
num_epochs: 2

# logging
wandb: true
wandb_entity: # update
wandb_project_name: # update
seed: 42
